# Generated by Django 4.1 on 2022-10-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0010_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operador',
        ),
    ]
