# Generated by Django 4.1 on 2022-10-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0011_delete_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('nota', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario_carga',
            field=models.CharField(max_length=61, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_tareas.area'),
            preserve_default=False,
        ),
    ]
