# Generated by Django 4.1 on 2022-10-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0013_alter_area_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
